"""alerts

Revision ID: f13c72052aba
Revises: l6m7n8o9p0q1
Create Date: 2026-04-30 10:21:40.071339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13c72052aba'
down_revision: Union[str, Sequence[str], None] = 'l6m7n8o9p0q1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add alert_mode with a server_default so existing rows are backfilled to
    # 'informative' before the NOT NULL constraint is applied — without this
    # Postgres rejects the ALTER TABLE because NULL values already exist.
    op.add_column('alert_preferences', sa.Column(
        'alert_mode',
        sa.String(length=20),
        nullable=False,
        server_default='informative',
    ))
    op.add_column('alert_preferences', sa.Column('periodic_review_freq', sa.String(length=20), nullable=True))
    op.drop_constraint('alert_preferences_user_id_key', 'alert_preferences', type_='unique')
    op.drop_index('ix_alert_preferences_user_id', table_name='alert_preferences')
    op.create_index(op.f('ix_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=True)
    op.drop_index('ix_alerts_user_unread', table_name='alerts', postgresql_where='(read_at IS NULL)')
    op.drop_index('uq_categories_name_system', table_name='categories', postgresql_where='(user_id IS NULL)')
    op.drop_index('uq_categories_name_user', table_name='categories', postgresql_where='(user_id IS NOT NULL)')
    op.drop_constraint('uq_preferences_user_id', 'preferences', type_='unique')
    op.drop_index('ix_preferences_user_id', table_name='preferences')
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=True)
    op.alter_column('transactions', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.create_index('ix_preferences_user_id', 'preferences', ['user_id'], unique=False)
    op.create_unique_constraint('uq_preferences_user_id', 'preferences', ['user_id'])
    op.create_index('uq_categories_name_user', 'categories', ['name', 'user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('uq_categories_name_system', 'categories', ['name'], unique=True, postgresql_where='(user_id IS NULL)')
    op.create_index('ix_alerts_user_unread', 'alerts', ['user_id', 'read_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.drop_index(op.f('ix_alert_preferences_user_id'), table_name='alert_preferences')
    op.create_index('ix_alert_preferences_user_id', 'alert_preferences', ['user_id'], unique=False)
    op.create_unique_constraint('alert_preferences_user_id_key', 'alert_preferences', ['user_id'])
    op.drop_column('alert_preferences', 'periodic_review_freq')
    op.drop_column('alert_preferences', 'alert_mode')
    # ### end Alembic commands ###
