"""add missing FK indexes

Revision ID: 47316e7a94a0
Revises: d7279509afb8
Create Date: 2026-08-02 09:15:49.604088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47316e7a94a0'
down_revision: Union[str, Sequence[str], None] = 'd7279509afb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bills_budget_category_id'), 'bills', ['budget_category_id'], unique=False)
    op.create_index(op.f('ix_bills_transaction_id'), 'bills', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_budget_categories_transaction_id'), 'budget_categories', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_debts_linked_transaction_id'), 'debts', ['linked_transaction_id'], unique=False)
    op.create_index(op.f('ix_debts_recurring_transaction_id'), 'debts', ['recurring_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_budget_category_id'), 'transactions', ['budget_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_budget_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_debts_recurring_transaction_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_linked_transaction_id'), table_name='debts')
    op.drop_index(op.f('ix_budget_categories_transaction_id'), table_name='budget_categories')
    op.drop_index(op.f('ix_bills_transaction_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_budget_category_id'), table_name='bills')
    # ### end Alembic commands ###
