"""baseline: current schema, replacing lost pre-history

Revision ID: 966113aa8a57
Revises:
Create Date: 2026-08-01

WHY THIS EXISTS
----------------
The original migration chain's root (`create_initial_tables`, plus 7 more
early migrations through `5dadb7844cf9_add_is_draft_and_planned_amount`)
was never committed to git -- only stale .pyc files in a local __pycache__
proved they ever existed. The old chain's actual root file
(4b9d636e9e03_refractor_budget_categories.py) had its down_revision
hand-edited to None to silence Alembic, even though its own docstring says
it revises the missing 5dadb7844cf9. Practical result: `alembic upgrade
head` could not rebuild this database from an empty Postgres instance.

That history is confirmed unrecoverable, so this migration replaces it:
autogenerated against a throwaway empty Postgres instance, diffed against
`app/models.py` (current source of truth), then hand-verified with a real
upgrade+downgrade round-trip against another empty database before being
committed. All pre-baseline migration files have been moved to
`alembic/legacy_pre_baseline/` for historical reference -- they are no
longer part of Alembic's active chain.

CIRCULAR FK NOTE
-----------------
`transactions.budget_category_id` -> `budget_categories.id` and
`budget_categories.transaction_id` -> `transactions.id` reference each
other. Autogenerate cannot pick a valid CREATE TABLE order for a genuine
two-way FK cycle, so both constraints were pulled out of their
`create_table()` calls and added via `op.create_foreign_key()` once both
tables exist. This is a mechanical fix (Cesar's call, 2026-08-01) --
it preserves the current bidirectional "hub" design as-is. Whether
`budget_categories` should keep its own `transaction_id`, given
`transactions.budget_category_id` already points the other way, is a
separate normalization question tracked under item #5, not resolved here.

PRODUCTION NOTE
-----------------
Supabase's live schema already matches this shape (nothing here should be
run as a real upgrade against it). Instead, mark it as already applied:
    alembic stamp 966113aa8a57
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '966113aa8a57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_consented', sa.Boolean(), nullable=False),
    sa.Column('telegram_active_mode', sa.Boolean(), nullable=False),
    sa.Column('pwa_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('pwa_push_subscription', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_time', sa.Time(), nullable=False),
    sa.Column('immediate_enabled', sa.Boolean(), nullable=False),
    sa.Column('bill_due_days', sa.Integer(), nullable=False),
    sa.Column('large_tx_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_balance_floor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alert_mode', sa.String(length=20), nullable=False),
    sa.Column('periodic_review_freq', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('fired_immediate', sa.Boolean(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('budget_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('transaction_name', sa.String(length=255), nullable=False),
    sa.Column('transaction_payment_method', sa.String(length=50), nullable=True),
    sa.Column('categories_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_categories_user_id'), 'budget_categories', ['user_id'], unique=False)
    # NOTE: transaction_id -> transactions.id FK added below via ALTER TABLE,
    # after 'transactions' exists -- budget_categories <-> transactions is a
    # genuine circular FK (each table references the other), so neither can
    # be created first with both constraints inline.
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.Enum('expense', 'income', 'savings', 'debt_payment', name='category_kind'), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_variable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('earmarked_funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earmarked_funds_user_id'), 'earmarked_funds', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('month_start', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('bank_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bank_balance_date', sa.Date(), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tracking_start_date', sa.Date(), nullable=True),
    sa.Column('show_balance_gap', sa.Boolean(), nullable=False),
    sa.Column('balance_reminder_day', sa.Integer(), nullable=True),
    sa.Column('balance_anchor_app', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=True)
    op.create_table('recurring_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.create_table('savings_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('goal_name', sa.String(length=100), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('income', 'expense', 'savings', 'debt_payment', 'transfer', name='transaction_type'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_amt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import', 'api_sync', 'bill_payment', 'savings_contribution', 'csv_import', 'cc_charge', 'debt_payment', name='source_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('budget_category_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)

    # Both halves of the circular FK are added here, now that both tables exist.
    op.create_foreign_key(
        'fk_budget_categories_transaction_id_transactions',
        'budget_categories', 'transactions',
        ['transaction_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_transactions_budget_category_id_budget_categories',
        'transactions', 'budget_categories',
        ['budget_category_id'], ['id'], ondelete='SET NULL',
    )
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('paid', 'unpaid', name='bill_status'), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('budget_category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('is_paid_off', sa.Boolean(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('show_amortization', sa.Boolean(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_cycle_end_day', sa.Integer(), nullable=True),
    sa.Column('card_network', sa.String(length=50), nullable=True),
    sa.Column('linked_transaction_id', sa.UUID(), nullable=True),
    sa.Column('total_installments', sa.Integer(), nullable=True),
    sa.Column('installments_paid', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recurring_transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_transaction_id'], ['recurring_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_user_id'), 'debts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_budget_category_id_budget_categories', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_budget_categories_transaction_id_transactions', 'budget_categories', type_='foreignkey')
    op.drop_index(op.f('ix_debts_user_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_earmarked_funds_user_id'), table_name='earmarked_funds')
    op.drop_table('earmarked_funds')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_budget_categories_user_id'), table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_preferences_user_id'), table_name='alert_preferences')
    op.drop_table('alert_preferences')
    # ### end Alembic commands ###
