"""restore legacy check constraints and partial unique indexes

Revision ID: c4201ebc19cc
Revises: 2f3494829eaf
Create Date: 2026-08-02 10:05:15.238183

WHY THIS EXISTS
----------------
5 real constraints only ever existed as raw SQL in the pre-baseline
migration chain (d2e3f4a5b6c7, b2c3d4e5f6a7) -- never declared in
models.py, so the 2026-08-02 baseline squash missed them entirely:

  - categories: uq_categories_name_system, uq_categories_name_user
    (partial unique indexes -- what actually enforces "one system
    category per name, one user category per name per user")
  - alerts: tier CHECK (1,2,3), severity CHECK (info/warning/critical),
    ix_alerts_user_unread (partial index for the unread-count query)

Found while answering a normalization question, doing a full sweep of
every raw-SQL migration in the archived chain against current models.py.
Now declared in models.py (Alert.__table_args__, Category.__table_args__)
so they're actual documented schema, not tribal knowledge in a migration
file -- and so future `alembic revision --autogenerate` runs see them as
intentional instead of drift to drop.

The 3 indexes were autogenerated correctly (SQLAlchemy Index with
postgresql_where IS autodetected). The 2 CHECK constraints were NOT --
a known Alembic limitation, added here by hand.

SAFETY: production likely already has some/all of these from the old
(now-archived) migration having run historically. Every statement here
uses IF NOT EXISTS / DO $$ guards, same technique the original migrations
used, so this is safe to run whether or not they already exist.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4201ebc19cc'
down_revision: Union[str, Sequence[str], None] = '2f3494829eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index(
        'ix_alerts_user_unread', 'alerts', ['user_id', 'read_at'],
        unique=False, postgresql_where=sa.text('read_at IS NULL'),
        if_not_exists=True,
    )
    op.create_index(
        'uq_categories_name_system', 'categories', ['name'],
        unique=True, postgresql_where=sa.text('user_id IS NULL'),
        if_not_exists=True,
    )
    op.create_index(
        'uq_categories_name_user', 'categories', ['name', 'user_id'],
        unique=True, postgresql_where=sa.text('user_id IS NOT NULL'),
        if_not_exists=True,
    )

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'alerts_tier_check'
                  AND conrelid = 'alerts'::regclass
            ) THEN
                ALTER TABLE alerts
                    ADD CONSTRAINT alerts_tier_check CHECK (tier IN (1, 2, 3));
            END IF;
        END
        $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'alerts_severity_check'
                  AND conrelid = 'alerts'::regclass
            ) THEN
                ALTER TABLE alerts
                    ADD CONSTRAINT alerts_severity_check
                        CHECK (severity IN ('info', 'warning', 'critical'));
            END IF;
        END
        $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_severity_check;")
    op.execute("ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_tier_check;")
    op.drop_index('uq_categories_name_user', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'), if_exists=True)
    op.drop_index('uq_categories_name_system', table_name='categories', postgresql_where=sa.text('user_id IS NULL'), if_exists=True)
    op.drop_index('ix_alerts_user_unread', table_name='alerts', postgresql_where=sa.text('read_at IS NULL'), if_exists=True)
