"""drop dead bill auto_detected column

Revision ID: d7279509afb8
Revises: 9440204d5132
Create Date: 2026-08-02 09:07:31.625212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7279509afb8'
down_revision: Union[str, Sequence[str], None] = '9440204d5132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'auto_detected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('auto_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
